# Generated by Django 5.2.16 on 2026-07-18 19:15

from django.db import migrations, models
from django.db.models import Count
from django.db.models.functions import Lower


def normalize_existing_users(apps, schema_editor):
    user_model = apps.get_model("accounts", "User")
    database = schema_editor.connection.alias
    collisions = list(
        user_model.objects.using(database)
        .annotate(normalized_email=Lower("email"))
        .values("normalized_email")
        .annotate(total=Count("id"))
        .filter(total__gt=1)
        .order_by("normalized_email")
        .values_list("normalized_email", flat=True)
    )
    if collisions:
        raise RuntimeError(
            "Cannot normalize account emails because case-insensitive collisions "
            f"exist: {', '.join(collisions)}"
        )

    users = (
        user_model.objects.using(database).all().only("pk", "email", "is_superuser", "is_validated")
    )
    for user in users.iterator():
        updates = {}
        normalized_email = user.email.lower()
        if user.email != normalized_email:
            updates["email"] = normalized_email
        if user.is_superuser and not user.is_validated:
            updates["is_validated"] = True
        if updates:
            user_model.objects.using(database).filter(pk=user.pk).update(**updates)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_validated",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(normalize_existing_users, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                Lower("email"),
                name="accounts_user_email_ci_unique",
            ),
        ),
    ]
