# Generated by Django 5.2.16 on 2026-07-18 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("access", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("variants", models.JSONField(default=list)),
                ("default_variant", models.CharField(max_length=80)),
            ],
            options={
                "ordering": ("key",),
            },
        ),
        migrations.CreateModel(
            name="FeatureRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("priority", models.PositiveIntegerField()),
                ("variant", models.CharField(max_length=80)),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("everyone", "Everyone"),
                            ("user", "User"),
                            ("role", "Role"),
                            ("group", "Organizational group"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="features.feature",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audience_feature_rules",
                        to="access.organizationalgroup",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_rules",
                        to="access.role",
                    ),
                ),
                (
                    "scope",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scoped_feature_rules",
                        to="access.organizationalgroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("priority", "pk"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("feature", "priority"), name="features_unique_rule_priority"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("audience", "everyone"),
                                ("group__isnull", True),
                                ("role__isnull", True),
                                ("user__isnull", True),
                            ),
                            models.Q(
                                ("audience", "user"),
                                ("group__isnull", True),
                                ("role__isnull", True),
                                ("user__isnull", False),
                            ),
                            models.Q(
                                ("audience", "role"),
                                ("group__isnull", True),
                                ("role__isnull", False),
                                ("user__isnull", True),
                            ),
                            models.Q(
                                ("audience", "group"),
                                ("group__isnull", False),
                                ("role__isnull", True),
                                ("user__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="features_rule_selected_audience",
                    ),
                ],
            },
        ),
    ]
